---
AWSTemplateFormatVersion: 2010-09-09

Description: Nested Fargate Stack deployment


Parameters:

  ProjectName:
    Description: Project Name (used for Tagging)
    Type: String    
  BucketName:
    Description: Bucket name where nested templates live
    Type: String
  ClusterName:
    Description: Fargate Cluster Name (will be exported for use with resources in this project)
    Type: String

  HelloWorldServiceName:
    Type: String
    Description: Name given to the service being run on the Fargate Cluster
  HelloWorldContainerName:
    Type: String
    Description: The name of a docker image that should be run from ECR
  HelloWorldContainerPort:
    Type: Number
    Description: What port number the application inside the docker container
  HelloWorldContainerCpu:
    Type: Number
    Description: How much CPU to give the container. 1024 is 1 CPU
  HelloWorldContainerMemory:
    Type: Number
    Description: How much memory in megabytes to give the container
  HelloWorldDesiredCount:
    Type: Number
    Description: How many copies of the service task to run
  HelloWorldHealthEndpoint:
    Type: String
    Description: Health Endpoint to target via Application load balancer health checks

  CodeRepositoryURL:
    Description: URL of the repo which contains CFN template.
    Type: String

  HelloWorldBuildspecLocation:
    Description: Location of buildspec configuration
    Type: String
  HelloWorldEnvironmentType:
    Description: Type of build environment to use for related builds.
    Type: String
    
  HelloWorldComputeType:
    Description: Compute resources the build project will use to build.
    Type: String
    
  HelloWorldBuildImage:
    Description: System Image identifier of the image to use for code build
    Type: String


Resources:

  baseFargate:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ProjectName:
          !Ref ProjectName
        ClusterName:
          !Ref ClusterName
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/resources/service-helloworld/cloudformation/infra/fargate-cluster.yaml'

  baseNetworking:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/resources/service-helloworld/cloudformation/infra/vpc-networking.yaml'

  helloWorldService:
    DependsOn: [ baseFargate, baseNetworking ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        ServiceName:
          !Ref HelloWorldServiceName
        VPCId:
          !GetAtt [ baseNetworking, Outputs.VPC ]
        PublicSubnetIDs:
          !GetAtt [ baseNetworking, Outputs.SubnetsPublic ]
        PrivateSubnetIDs:
          !GetAtt [ baseNetworking, Outputs.SubnetsPrivate ]
        FargateCluster:
          !GetAtt [ baseFargate, Outputs.FargateCluster ]
        ContainerName:
          !Ref HelloWorldContainerName
        ContainerPort:
          !Ref HelloWorldContainerPort
        ContainerCpu:
          !Ref HelloWorldContainerCpu
        ContainerMemory:
          !Ref HelloWorldContainerMemory
        DesiredCount:
          !Ref HelloWorldDesiredCount
        HealthEndpoint:
          !Ref HelloWorldHealthEndpoint
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/resources/service-helloworld/cloudformation/infra/fargate-service.yaml'

  HelloWorldCodebuild:
    DependsOn: [ baseFargate, baseNetworking, helloWorldService ]
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        VPC:
          !GetAtt [ baseNetworking, Outputs.VPC ]
        SubnetIDs:
          !GetAtt [ baseNetworking, Outputs.SubnetsPrivate ]
        FargateCluster:
          !GetAtt [ baseFargate, Outputs.FargateCluster ]
        FargateService:
          !Ref HelloWorldServiceName
        CodeRepositoryURL:
          !Ref CodeRepositoryURL
        BuildspecLocation:
          !Ref HelloWorldBuildspecLocation
        ImageRepoName:
          !Ref HelloWorldContainerName
        EnvironmentType:
          !Ref HelloWorldEnvironmentType
        ComputeType:
          !Ref HelloWorldComputeType
        BuildImage:
          !Ref HelloWorldBuildImage
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/resources/service-helloworld/cloudformation/build/codebuild.yaml'


Outputs:

  HelloWorldApiEndpoint:
    Description: API Endpoint for the HelloWorld Service
    Value: !GetAtt [ helloWorldService, Outputs.EndpointUrl ]
